              OrdererOrgs:
                - Name: Orderer
                  Domain: acme.com
                  Specs:
                    - Hostname: orderer
              PeerOrgs:
                - Name: Org1
                  Domain: org1.acme.com
                  Template:
                    Count: 1
                  Users:
                    Count: 1
                - Name: Org2
                  Domain: org2.acme.com
                  Template:
                    Count: 1
                  Users:
                    Count: 1
                - Name: Org3
                  Domain: org3.acme.com
                  Template:
                    Count: 1
                  Users:
                    Count: 1